### ISSUE TITLE
demo from README.md ends with Error

### ISSUE THREAD

**Issue by oleiba** [Synthetixio/synthetix-js#36]
From the README (I just changed the networkId to be Ropsten):
```js
const { SynthetixJs } = require('synthetix-js');
//parameters: default provider, default networkId, private key as a string
const networkId = 3;  // Ropsten
const signer = new SynthetixJs.signers.PrivateKey(
  null,
  networkId,
  '0x0123456789012345678901234567890123456789012345678901234567890123'
);
const snxjs = new SynthetixJs({ networkId, signer });
const sUSD = snxjs.utils.toUtf8Bytes('sUSD');

async function run() {
  const totalSupply = await snxjs.Synthetix.totalSupply();
  const snxTotalSupply = snxjs.utils.formatEther(totalSupply);
  console.log('snxTotalSupply', snxTotalSupply);

  //issue 100 synths (will throw if insufficient funds for gas)
  try {
    const txObj = await snxjs.Synthetix.issueSynths(sUSD, snxjs.util.parseEther('100')); //execute transaction (requires gas)
    console.log('transaction hash', txObj.hash);
  } catch (e) {
    console.log(e);
  }
}

run();
```

Execution ends with:
```
Error: unknown transaction override _hex
    at Contract.issueSynths (/Users/odedleiba/MyWorkspace/synthetix-playground/node_modules/synthetix-js/dist/main.node.js:11375:27)
    at ropsten_Synthetix_Synthetix.issueSynths (/Users/odedleiba/MyWorkspace/synthetix-playground/node_modules/synthetix-js/dist/main.node.js:46304:32)
    at run (/Users/odedleiba/MyWorkspace/synthetix-playground/index.js:26:45)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

This is because the signature of `issueSynths` is:
```js
this.issueSynths = async (amount, txParams) {...}
```
So it seems that `sUSD` and `snxjs.util.parseEther('100')` do not apply to the parameters requirement.

**Comment by justinjmoses** [comment]
Thanks for reporting @oleiba - I just updated the documentation to include the changes from [SIP-29](https://sips.synthetix.io/sips/sip-29). Please reopen if you notice other issues with the docs. 🙏

**Comment by oleiba** [comment]
There's something I am not sure here: https://github.com/Synthetixio/synthetix-js#example-of-minting-stablecoinsusd-with-private-key-signer.

1. Why is that minting specifically sUSD? there's no mention of sUSD in the code.
2. In order to mint sUSD, shouldn't it assume that the sending address has SNX on it? (it should lock-up SNX as collateral in order to mint it, to my understanding)

**Comment by justinjmoses** [comment]
1. It used to be the case that you could choose which synth to mint into, but we removed that in our Vega release with https://sips.synthetix.io/sips/sip-29 
2. Correct. That example wouldn't work as-is because there is no SNX in that account. You'd need to supply some SNX for it to be able to issue. For example, here's the script we run run on each testnet whenever a change is detected in one of our testnet branches: https://github.com/Synthetixio/synthetix/blob/master/test/testnet/index.js#L170-L190 - the new account is given testnet ETH and testnet SNX, before it starts to issue.
